### ISSUE TITLE
Failed to import openseespy

### ISSUE THREAD

**Issue by awa5114** [OpenSees/OpenSees#383]
I am trying to install openseespy on my windows machine and am running into problems:
```

>>> import openseespy.opensees as ops
Traceback (most recent call last):
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\11204496_Turnkey\lib\site-packages\openseespy\opensees\__init__.py", line 21, in <module>
    from openseespy.opensees.win.opensees import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\11204496_Turnkey\lib\site-packages\openseespy\opensees\__init__.py", line 26, in <module>
    'Failed to import openseespy. Anaconda is recommended https://www.anaconda.com/distribution/')
RuntimeError: Failed to import openseespy. Anaconda is recommended https://www.anaconda.com/distribution/

```

I am using an anaconda environment with 64-bit  python 3.7.6 installed. I installed openseespy as instructed by the documentation using pip. Please help?

**Comment by awa5114** [comment]
I have  also posted a related question in [stackexchange ](https://stackoverflow.com/questions/62753475/python-library-apparently-not-properly-setting-paths-to-its-own-dlls)

**Comment by mhscott** [comment]
Please post this issue here: https://github.com/zhuminjie/openseespy/issues
